---
- name: Ensure EPICS packages are installed
  apt:
    name: "{{ epics_packages }}"
    state: "{{ epics_packages_state }}"
    install_recommends: "{{ epics_install_recommends }}"
  become: true
  register: apt_packages_result
  until: apt_packages_result is success
  retries: 5
  delay: 2

- name: Ensure Python EPICS packages are installed
  pip:
    name: "{{ epics_pip_packages }}"
    state: "{{ epics_pip_packages_state }}"
    executable: "{{ pip_executable }}"
  environment:
    EPICS_BASE: "{{ epics_base_dir }}"
    EPICS_HOST_ARCH: "{{ epics_host_arch }}"
  become: true
  register: epics_pip_packages_result
  until: epics_pip_packages_result is success
  retries: 5
  delay: 2

- name: Ensure Python2 EPICS packages are installed
  pip:
    name: "{{ epics_pip_packages }}"
    state: "{{ epics_pip_packages_state }}"
    executable: "{{ pip2_executable }}"
  environment:
    EPICS_BASE: "{{ epics_base_dir }}"
    EPICS_HOST_ARCH: "{{ epics_host_arch }}"
  become: true
  register: epics_pip_packages_result
  until: epics_pip_packages_result is success
  retries: 5
  delay: 2

- name: Ensure EPICS environment is installed
  template:
    src: "{{ item.filename }}.j2"
    dest: "{{ item.pathname }}/{{ item.filename }}"
    owner: root
    group: root
    mode: 0644
  become: true
  with_items:
    - "{{ epics_config_files }}"
  when: apt_packages_result is success and
    epics_config_files_state == 'present'

- name: Ensure EPICS environment is not installed
  file:
    path: "{{ item.pathname }}/{{ item.filename }}"
    state: absent
  become: true
  with_items:
    - "{{ epics_config_files }}"
  when: apt_packages_result is success and
    epics_config_files_state == 'absent'
