---
dependency:
  name: galaxy
lint: |
  set -e
  yamllint .
  ansible-lint
  flake8
provisioner:
  name: ansible
  inventory:
    group_vars:
      default_group:
verifier:
  name: testinfra
  options:
    verbose: true
driver:
  name: docker
platforms:
  - name: ansible-role-epics-instance
    image: "${MOLECULE_DISTRO:-debian:stretch}"
    groups:
      - default_group
    dns_servers: ["${DNS_SERVER1}", "${DNS_SERVER2}"]
